### ISSUE TITLE
Add .cf-extensions to your repo to be listed in cloudfoundry-incubator.cf-extensions

### ISSUE THREAD

**Issue by maximilien** [cloudfoundry-incubator/credhub#18]
Add `.cf-extensions` file to your repo so that it shows correctly in the [CF-Extensions](https://github.com/cloudfoundry-incubator/cf-extensions) hub and [catalog](https://cloudfoundry-incubator.github.io/cf-extensions/).

```json
{
  "lead_company": "ADD LEAD COMPANY HERE",
  "contact_email": "contact@lead-company.com",
  "description": "ADD DESCRIPTION HERE",
  "tracker_url": "https://www.pivotaltracker.com",
  "proposal_url": "https://docs.google.com/document/d/1cpyBmds7WYNLKO1qkjhCdS8bNSJjWH5MqTE-h1UCQkQ/edit?usp=sharing",
  "proposed_date": "2017-08-29 10:31:52.56862848 -0700 PDT"
}
```
or
```yaml
lead_company: ADD LEAD COMPANY HERE
contact_email: contact@lead-company.com
description: ADD DESCRIPTION HERE
tracker_url: https://www.pivotaltracker.com
proposal_url: https://docs.google.com/document/d/1cpyBmds7WYNLKO1qkjhCdS8bNSJjWH5MqTE-h1UCQkQ/edit?usp=sharing
proposed_date: 2017-08-29 10:31:52.56862848 -0700 PDT

```

This is a JSON or YAML formatted file. The default values in the file are for you to get started. You should edit to match your project's data.

For example, the field `tracker_url` should contain your project's tracker URL, and so on.

*FINAL NOTES*

You may also add two more optional fields: `logo_url` and `icon_url` pointing to images for your logo and icon respectively.

For best results your images should be in JPG or PNG file formats and their sizes around 200x300 pixels for logo and 32x32 pixels for icon.
