### ISSUE TITLE
read access to /api/v1/data  requires credhub.write permissions

### ISSUE THREAD

**Issue by jsievers** [cloudfoundry-incubator/credhub#62]
What version of the credhub server you are using?
https://github.com/pivotal/credhub-release/releases/tag/2.5.6

What version of the credhub cli you are using?
CLI Version: 2.6.1

If you were attempting to accomplish a task, what was it you were attempting to do?

we have credhub clients that should only be able to read credentials, not write them. we want to restrict the permissions of those clients to credhub.read.

What did you expect to happen?

a call to REST endpoint https://credhub-api.cfapps.io/version/2.5/#_get_a_credential_by_name using a bearer token with only credhub.read permissions should succeed

What was the actual behavior?

HTTP 403 error: Bearer error="insufficient_scope", error_description="Insufficient scope for this resource", scope="credhub.write"

curl example log:

```
curl -kv -H "Authorization: Bearer ${TOKEN}" 'https://10.250.2.9:8844/api/v1/data?current=true&name=%2Fexample-password'
*   Trying 10.250.2.9...
* Connected to 10.250.2.9 (10.250.2.9) port 8844 (#0)
* found 166 certificates in /etc/ssl/certs/ca-certificates.crt
* found 610 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / DHE_RSA_AES_128_GCM_SHA256
*        server certificate verification SKIPPED
*        server certificate status verification SKIPPED
*        common name: 10.250.2.9 (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: RSA
*        certificate version: #3
*        subject: C=USA,O=Cloud Foundry,CN=10.250.2.9
*        start date: Wed, 11 Dec 2019 13:29:06 GMT
*        expire date: Thu, 10 Dec 2020 13:29:06 GMT
*        issuer: C=USA,O=Cloud Foundry,CN=CredHub CA
*        compression: NULL
* ALPN, server did not agree to a protocol
> GET /api/v1/data?current=true&name=%2example-password HTTP/1.1
> Host: 10.250.2.9:8844
> User-Agent: curl/7.47.0
> Accept: */*
> Authorization: Bearer <REDACTED>
< HTTP/1.1 403
< Pragma: no-cache
< WWW-Authenticate: Bearer error="insufficient_scope", error_description="Insufficient scope for this resource", scope="credhub.write"
< Cache-Control: no-store
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-Frame-Options: DENY
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Tue, 07 Jan 2020 16:22:28 GMT
<
* Connection #0 to host 10.250.2.9 left intact
```

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by ankeesler** [comment]
@jsievers - thank you for filing this issue. I understand your confusion here - it has confused me too. What is the negative impact for you to have to add both `credhub.read` and `credhub.write` to your UAA identity? That seems like the fastest way to get you unblocked. If you do want your identity to only be able to read data, we recommend you giving that actor only the `read` operation in the `credhub.authorization.permissions` BOSH property.

**Comment by jsievers** [comment]
I would like to restrict access permissions to read only for *all* credentials stored in credhub.

according to

https://github.com/pivotal/credhub-release/blob/b3ddcbbf000634c7ad3745f26b74f9f20cffc40a/jobs/credhub/spec#L234-L247

would something like this accomplish it?

```
credhub:
  authorization:
    permissions:
    - path: /
       actors:
        - uaa-client:my-readonly-client-id
        operations:
        - read
```

**Comment by ankeesler** [comment]
Almost - you would need to update the `path` to be `/*`. A `path` without a `*` means the actor can read the single credential at that path. Adding a `*` means that the actor can read all credentials with that path prefix.

Other than that one update to the `path`, your YAML above does indeed give read only access to the UAA client named `my-readonly-client-id`.

**Comment by jsievers** [comment]
thanks! this worked for me . I also had to add explicit permissions for the admin client but I guess that's normal if ACLs are enabled

```
    credhub:
      authorization:
        permissions:
        - path: /*
          actors:
          - uaa-client:credhub_reader
          operations:
          - read
        - path: /*
          actors:
          - uaa-client:credhub_admin
          operations:
          - read
          - write
          - delete
          - read_acl
          - write_acl
```
